import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/header";
import { ThemeProvider } from "@/components/layout/theme-provider";
import { ModeToggle } from "@/components/ui/theme-toggle";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`h-screen  ${inter.className}`}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<Header />
					<section className="mx-auto max-w-screen-xl p-3">{children}</section>
					<footer className="text-center text-sm text-primary">
						<p>© 2024</p>
						<header className="sticky top-0 z-[1] mx-auto flex w-full max-w-screen-xl flex-wrap items-center justify-end p-3 font-sans font-bold uppercase text-primary ">
							<ModeToggle />
						</header>
					</footer>
				</ThemeProvider>
			</body>
		</html>
	);
}
