import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/layout/header";
import { ThemeProvider } from "@/components/layout/theme-provider";
import { ModeToggle } from "@/components/ui/theme-toggle";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`h-screen  ${inter.className} `}>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<Header />
					<section className="mx-auto h-full max-w-6xl p-3">{children}</section>
					<footer className="mx-auto max-w-6xl pb-6 text-center text-sm text-primary">
						<div className="flex w-full items-center justify-between gap-4 p-3 text-left text-primary">
							<div className="mx-auto flex flex-wrap gap-8  p-3 text-left text-primary">
								<ul>
									<li>Terapia</li>
									<li>Cennik</li>
									<li>Umów wizytę</li>
								</ul>
								<ul>
									<li>Materiały</li>
									<li>Cennik</li>
									<li>Umów wizytę</li>
								</ul>
								<ul>
									<li>Materiały</li>
									<li>Cennik</li>
									<li>Umów wizytę</li>
								</ul>
							</div>
							<div className="flex-1"></div>
							<ModeToggle />
						</div>
						<p>© Anna Kłobuchowska 2024</p>
					</footer>
				</ThemeProvider>
			</body>
		</html>
	);
}
